,watchfiles error

diff --git a/bin/,watchfiles b/bin/,watchfiles
--- a/bin/,watchfiles
+++ b/bin/,watchfiles
@@ -11,7 +11,7 @@ watchfiles() {
     shift
     while true; do
         if find . -name "$pattern" -newer "$tmp" | grep . ; then
-            "$@"
+            "$@" || printf >&2 "ERROR code: $?\n"
             touch "$tmp"
         fi
         sleep 0.1
